'use client';

import { useEffect, useState } from 'react';
import { portfolio } from '../data/portfolio';

function Penguin({ className = '' }) { return <div className={`penguin ${className}`} aria-hidden="true"><i /><b /><em /></div>; }
function Cube({ className = '' }) { return <div className={`minecraft-cube ${className}`} aria-hidden="true"><i className="cube-top" /><i className="cube-right" /><i className="cube-front" /></div>; }

export default function Home() {
  const [berries, setBerries] = useState(0);
  const [soundOn, setSoundOn] = useState(false);
  const assetBase = process.env.NEXT_PUBLIC_BASE_PATH || '';
  useEffect(() => {
    const onMove = (event) => { const glow = document.querySelector('.cursor-glow'); if (glow) { glow.style.left = `${event.clientX}px`; glow.style.top = `${event.clientY}px`; } };
    const onScroll = () => document.querySelector('.site-header')?.classList.toggle('scrolled', window.scrollY > 25);
    window.addEventListener('pointermove', onMove); window.addEventListener('scroll', onScroll);
    const stage = document.querySelector('.hero-stage');
    const avatar = new Image(); avatar.className = 'yashi-avatar'; avatar.alt = 'Yashi, the pixel AI explorer';
    avatar.onload = () => { const canvas = document.createElement('canvas'); canvas.width = avatar.naturalWidth; canvas.height = avatar.naturalHeight; const context = canvas.getContext('2d'); context.drawImage(avatar, 0, 0); const pixels = context.getImageData(0, 0, canvas.width, canvas.height); for (let index = 0; index < pixels.data.length; index += 4) { if (pixels.data[index] > 230 && pixels.data[index + 1] < 60 && pixels.data[index + 2] > 190) pixels.data[index + 3] = 0; } context.putImageData(pixels, 0, 0); avatar.onload = null; avatar.src = canvas.toDataURL('image/png'); };
    avatar.src = `${assetBase}/images/yashi-pixel-source.png`; stage?.appendChild(avatar);
    const connect = document.querySelector('.hero-actions .ghost'); if (connect) { connect.href = `mailto:${portfolio.email}`; connect.textContent = "let's connect"; }
    const links = document.querySelector('.header-links'); let instagram; if (portfolio.instagram && links) { instagram = document.createElement('a'); instagram.href = portfolio.instagram; instagram.target = '_blank'; instagram.rel = 'noreferrer'; instagram.textContent = 'Instagram ->'; links.prepend(instagram); }
    const certificates = document.createElement('section'); certificates.className = 'certifications section-shell'; certificates.innerHTML = `<p class="eyebrow">06 / BADGES UNLOCKED</p><h2>Proof of <em>curiosity.</em></h2><div class="certificate-grid">${portfolio.certifications.map((item) => `<span>${item}</span>`).join('')}</div>`; document.querySelector('#off-duty')?.before(certificates);
    const gameBox = document.querySelector('.game-box'); const vibe = document.createElement('p'); vibe.className = 'good-vibe'; vibe.textContent = 'Feed a berry for a tiny good-human reminder.'; gameBox?.append(vibe); let quoteIndex = 0; const berryButton = gameBox?.querySelector('button'); const giveVibe = () => { vibe.textContent = portfolio.quotes[quoteIndex]; quoteIndex = (quoteIndex + 1) % portfolio.quotes.length; }; berryButton?.addEventListener('click', giveVibe);
    const snakeGame = document.createElement('div'); snakeGame.className = 'snake-game'; let position = 1; const jumps = { 3: 16, 8: 22, 19: 7, 24: 12 }; const renderBoard = (message = 'Roll to begin.') => { snakeGame.innerHTML = `<p class="eyebrow">MINI GAME / SNAKE & LADDERS</p><div class="snake-grid">${Array.from({ length: 25 }, (_, index) => { const cell = 25 - index; return `<span class="${cell === position ? 'player' : ''}">${cell}${jumps[cell] ? (jumps[cell] > cell ? ' L' : ' S') : ''}</span>`; }).join('')}</div><button class="button primary game-roll">roll dice</button><p class="snake-status">${message}</p>`; }; renderBoard(); gameBox?.after(snakeGame); const roll = () => { const dice = Math.floor(Math.random() * 6) + 1; position = Math.min(25, position + dice); const destination = jumps[position]; if (destination) position = destination; renderBoard(position === 25 ? 'You won the map. Legendary!' : `You rolled ${dice}. Keep going!`); snakeGame.querySelector('.game-roll')?.addEventListener('click', roll); }; snakeGame.querySelector('.game-roll')?.addEventListener('click', roll);
    const sideQuests = document.createElement('aside'); sideQuests.className = 'side-quests'; sideQuests.innerHTML = `<p class="eyebrow">YASHI'S SIDE QUESTS</p>${portfolio.interests.map((interest, index) => `<article><b>${interest}</b><span>${portfolio.interestNotes[index]}</span></article>`).join('')}`; snakeGame.after(sideQuests);
    const gallery = document.createElement('section'); gallery.className = 'yashi-gallery section-shell'; gallery.innerHTML = `<p class="eyebrow">YASHI / PHOTO DROP</p><h2>Little frames,<br /><em>big feelings.</em></h2><div class="gallery-grid">${['01','02','03','04'].map((number) => `<figure><img src="${assetBase}/images/yashi-gallery-${number}.jpeg" alt="Yashi portrait ${number}" /><figcaption>MEMORY // ${number}</figcaption></figure>`).join('')}</div>`; document.querySelector('#off-duty')?.after(gallery);
    const credit = document.querySelector('footer span'); const originalCredit = credit?.textContent; if (credit) credit.textContent = 'Copyright 2026 - Created by Yashashwini Awate';
    return () => { window.removeEventListener('pointermove', onMove); window.removeEventListener('scroll', onScroll); berryButton?.removeEventListener('click', giveVibe); avatar.remove(); instagram?.remove(); certificates.remove(); vibe.remove(); snakeGame.remove(); sideQuests.remove(); gallery.remove(); if (credit) credit.textContent = originalCredit; };
  }, []);

  return <>
    <div className="cursor-glow" aria-hidden="true" />
    <header className="site-header"><a className="brand" href="#top"><span>Y</span>AWATE.EXE</a><nav><a href="#about">about</a><a href="#quests">quests</a><a href="#toolkit">tools</a><a href="#off-duty">off-duty</a></nav><div className="header-links"><a href={portfolio.github} target="_blank" rel="noreferrer">GitHub -&gt;</a><a href={portfolio.linkedin} target="_blank" rel="noreferrer">LinkedIn -&gt;</a><a href={portfolio.cv} target="_blank" rel="noreferrer">CV -&gt;</a><a className="contact-mini" href={`mailto:${portfolio.email}`}>say hello</a></div></header>
    <main id="top">
      <section className="hero section-shell"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> {portfolio.availability}</p><div className="role-chip">AI / ML EXPLORER</div><h1>human-first<br /><em>intelligence.</em></h1><p className="intro">{portfolio.intro}</p><div className="hero-actions"><a className="button primary" href="#quests">enter my world</a><a className="button ghost" href={portfolio.cv} target="_blank" rel="noreferrer">view CV -&gt;</a></div><div className="coordinates"><span>WORLD SEED: 2001-NOW</span><span>MODE: CREATIVE / PRECISE</span></div></div><div className="hero-stage"><div className="scan-lines" /><div className="moon" /><div className="star star-one" /><div className="star star-two" /><div className="star star-three" /><Cube className="cube-one" /><Cube className="cube-two" /><div className="mountain mountain-back" /><div className="mountain mountain-front" /><div className="tree tree-one"><b /><i /></div><div className="tree tree-two"><b /><i /></div><div className="video-frame"><div className="recording">REC</div><video autoPlay muted loop playsInline poster={portfolio.photos.hero}><source src={portfolio.video} type="video/mp4" /></video><span className="frame-label">FIELD NOTES #01<br />FILMED BY YASH</span></div><div className="floating-stat stat-one"><b>+35%</b><span>DATA EFFICIENCY</span></div><div className="floating-stat stat-two"><b>4.7M</b><span>BIKE TRIPS EXPLORED</span></div><Penguin className="penguin-hero" /><div className="sign">WELCOME<br />TRAVELER</div></div><div className="scroll-cue">SCROLL TO EXPLORE</div></section>
      <section id="about" className="about section-shell"><p className="eyebrow">01 / PLAYER PROFILE</p><div className="about-grid"><h2>I like data with<br /><em>a pulse.</em></h2><div><p className="large-copy">{portfolio.about}</p><p>{portfolio.aboutDetail}</p><div className="badge-row">{portfolio.seeking.map((role) => <span key={role}>* {role.toUpperCase()}</span>)}</div></div></div></section>
      <section id="quests" className="quests section-shell"><div className="section-top"><div><p className="eyebrow">02 / QUEST LOG</p><h2>Things I've<br /><em>made matter.</em></h2></div><p className="section-note">SELECT A MISSION<br />TO SEE THE STORY</p></div><div className="quest-grid">{portfolio.projects.map((project) => <article className={`quest-card ${project.theme}`} key={project.number}><div className="quest-no">QUEST {project.number}</div><div className="card-icon">{project.icon}</div><p className="tag">{project.type}</p><h3>{project.title.split('\n').map((line) => <span key={line}>{line}<br /></span>)}</h3><p>{project.description}</p><span className="card-arrow">-&gt;</span></article>)}</div></section>
      <section className="experience section-shell"><p className="eyebrow">03 / MY PATH SO FAR</p><div className="path-header"><h2>Experience, but<br /><em>make it a journey.</em></h2><Penguin className="penguin-path" /></div><div className="timeline">{portfolio.experience.map((job) => <article key={job.dates}><span>{job.dates}</span><div><h3>{job.role}</h3><p>{job.company}</p></div><p>{job.detail}</p></article>)}</div></section>
      <section id="toolkit" className="toolkit section-shell"><div className="toolkit-copy"><p className="eyebrow">04 / INVENTORY</p><h2>My favorite<br /><em>power-ups.</em></h2><p>Technical enough to build it. Curious enough to keep asking why.</p></div><div className="inventory">{portfolio.skills.map((skill) => <button key={skill}>{skill}</button>)}</div></section>
      <section id="off-duty" className="off-duty section-shell"><div className="off-grid"><div className="photo-card"><img src={portfolio.photos.hero} alt="Yashashwini beneath a lush green canopy" /><span>IRL / 2026</span></div><div className="off-copy"><p className="eyebrow">05 / WHEN I LOG OFF</p><h2>Collecting tiny<br /><em>beautiful things.</em></h2><p>When I'm not thinking in models and metrics, I'm recording music, watching light change through my Insta360 GO 3S, or wandering somewhere green with a camera.</p><div className="interests">{portfolio.interests.map((interest) => <span key={interest}>* {interest}</span>)}</div><p className="soft-note">I make room for both rest and momentum. The work still gets made.</p></div></div></section>
      <section className="game section-shell"><div><p className="eyebrow">BONUS LEVEL / PENGUIN SNACK BAR</p><h2>A tiny <em>break.</em></h2><p>Feed the pixel penguin berries. It is research-backed emotional infrastructure.</p></div><div className="game-box"><Penguin className="game-penguin" /><div className="berry-count">BERRIES: {berries}</div><button className="button primary" onClick={() => setBerries((count) => count + 1)}>give berry +1</button>{berries >= 10 && <p className="achievement">ACHIEVEMENT UNLOCKED: BEST HUMAN</p>}</div></section>
      <section className="contact section-shell"><div className="contact-penguins"><Penguin className="p-one" /><Penguin className="p-two" /></div><p className="eyebrow">END OF MAP / START OF SOMETHING</p><h2>Got a good<br />quest <em>for me?</em></h2><a className="button primary big" href={`mailto:${portfolio.email}`}>let's build it</a><p className="email">{portfolio.email} / {portfolio.location}</p></section>
    </main>
    <footer><span>(c) 2026 {portfolio.name.toUpperCase()}</span><span>MADE WITH CURIOSITY + A FEW PIXELS</span><span><a href={portfolio.github} target="_blank" rel="noreferrer">GITHUB</a> / <a href={portfolio.linkedin} target="_blank" rel="noreferrer">LINKEDIN</a> / <a href={portfolio.cv} target="_blank" rel="noreferrer">CV</a></span><button aria-pressed={soundOn} onClick={() => setSoundOn((on) => !on)}>SOUND: {soundOn ? 'ON' : 'OFF'}</button></footer>
  </>;
}
